<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\majestic-player.core\majestic-player.core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DynamicData" Version="9.2.1" />
		<PackageReference Include="LibVLCSharp" Version="3.9.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.4" />
		<PackageReference Include="MonoTorrent" Version="3.0.2" />
		<PackageReference Include="ReactiveUI" Version="20.2.45" />
		<PackageReference Include="TagLibSharp" Version="2.3.0" />
		<PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
	</ItemGroup>

	<PropertyGroup>
		<RootNamespace>majestic_player.infrastructure</RootNamespace>
		<Nullable>enable</Nullable>
		<TargetFramework>net9.0</TargetFramework>
		
	</PropertyGroup>

</Project>